//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_LRAP_Template_WP.Institution_List_Template_WP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class Institution_List_Template_WP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Label Label1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal Literal1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(Institution_List_Template_WP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "Label1";
            @__ctrl.Text = "Label";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlLiteral1() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.Literal1 = @__ctrl;
            @__ctrl.ID = "Literal1";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::test_LRAP_Template_WP.Institution_List_Template_WP.Institution_List_Template_WP @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<link rel=""stylesheet"" type=""text/css"" href=""//cdn.datatables.net/1.10.0/css/jquery.dataTables.css"">
<script type=""text/javascript"" src=""//code.jquery.com/jquery-1.10.2.min.js""></script>
<script type=""text/javascript"" src=""//cdn.datatables.net/1.10.0/js/jquery.dataTables.js""></script>
<script type=""text/javascript"" src=""//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js""></script>
<link type=""text/css"" href=""//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"" rel=""stylesheet"" />
<script type=""text/javascript"" src=""//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js""></script>

"));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlLabel1();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControlLiteral1();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/javascript\">\r\n    function LrapController($scope, $filter," +
                        " $http) {\r\n        \r\n\r\n        $scope.GetCurrentDate = function () {\r\n          " +
                        "  var today = new Date();\r\n            var dd = today.getDate();\r\n            va" +
                        "r mm = today.getMonth() + 1; //January is 0!\r\n            var yyyy = today.getFu" +
                        "llYear();\r\n\r\n            if (dd < 10) {\r\n                dd = \'0\' + dd\r\n        " +
                        "    }\r\n\r\n            if (mm < 10) {\r\n                mm = \'0\' + mm\r\n            " +
                        "}\r\n\r\n            today = yyyy + \'\' + mm + \'\' + dd;\r\n            //alert(today);\r" +
                        "\n            return today;\r\n        }\r\n\r\n        $scope.InstitutionForm = {\r\n   " +
                        "         CONTRACT_DATE: FormatDate(\"\" + $scope.GetCurrentDate()),\r\n            V" +
                        "ALIDATION_TEXT: []\r\n        };\r\n       \r\n        $scope.InstitutionStatusOptions" +
                        " = [\r\n             {\r\n                 \"id\": \"Active\",\r\n                 \"label\"" +
                        ": \"Active\"\r\n             },\r\n             {\r\n                 \"id\": \"Not Active\"" +
                        ",\r\n                 \"label\": \"Not Active\"\r\n             }\r\n        ];\r\n\r\n       " +
                        " function FormatDate(date) {\r\n            var returnString = \"\";\r\n            if" +
                        " (!isNullOrWhiteSpace(date)) {\r\n                var year = date.substring(0, 4);" +
                        "\r\n                var month = date.substring(4, 6);\r\n                var day = d" +
                        "ate.substring(6, 8);\r\n\r\n                returnString = month + \"/\" + day + \"/\" +" +
                        " year;\r\n            }\r\n            return returnString;\r\n        }\r\n\r\n        fu" +
                        "nction FormatSqlDate(date) {\r\n            var returnDate = \"\";\r\n            var " +
                        "zero = \"0\";\r\n            var twenty = \"20\";\r\n            try {\r\n                " +
                        "//alert(\"|\" + date + \"|\");\r\n                if (!isNullOrWhiteSpace(date)) {\r\n  " +
                        "                  // alert(\"pas\");\r\n                    var dates = date.split(\'" +
                        "/\');\r\n                    var year = (dates[2].length == 2 ? twenty.concat(dates" +
                        "[2]) : dates[2]);\r\n                    var month = (dates[0].length != 2 ? zero." +
                        "concat(dates[0]) : dates[0]);\r\n                    var day = (dates[1].length !=" +
                        " 2 ? zero.concat(dates[1]) : dates[1]);\r\n\r\n                    returnDate = year" +
                        " + month + day;\r\n                }\r\n            }\r\n            catch (err) {\r\n  " +
                        "              throw new Error(\"Error Parsing SqlDate From Display Date: Date mus" +
                        "t be in the format of MM/dd/YYYY \");\r\n            }\r\n\r\n            return return" +
                        "Date;\r\n        }\r\n\r\n\r\n\r\n\r\n        \r\n\r\n        /* nEW ANGULAR JS FUNCTONS */\r\n\r\n " +
                        "       $scope.GetCurrentDate = function () {\r\n            var today = new Date()" +
                        ";\r\n            var dd = today.getDate();\r\n            var mm = today.getMonth() " +
                        "+ 1; //January is 0!\r\n            var yyyy = today.getFullYear();\r\n\r\n           " +
                        " if (dd < 10) {\r\n                dd = \'0\' + dd\r\n            }\r\n\r\n            if " +
                        "(mm < 10) {\r\n                mm = \'0\' + mm\r\n            }\r\n\r\n            today =" +
                        " yyyy + \'\' + mm + \'\' + dd;\r\n            //alert(today);\r\n            return toda" +
                        "y;\r\n        }\r\n        $scope.HideModal = function (jqueryTargetModal) {\r\n      " +
                        "      // alert(\"HELLO\");\r\n            $(jqueryTargetModal).modal(\'hide\');\r\n     " +
                        "       //SuccessToast();\r\n        }\r\n\r\n\r\n        /*Institution Functions */\r\n\r\n " +
                        "       $scope.UpdateInstitution = function () {\r\n\r\n            try {\r\n          " +
                        "      showToaster(\'New Institution \', \'Updating...\');\r\n                var Insti" +
                        "tutionObject = {\r\n                    INSTITUTION_NAME: $scope.InstitutionForm.I" +
                        "NSTITUTION_NAME,\r\n                    CITY: $scope.InstitutionForm.CITY,\r\n      " +
                        "              STATE_PROVINCE: $scope.InstitutionForm.STATE_PROVINCE,\r\n          " +
                        "          SHORT_NAME: $scope.InstitutionForm.SHORT_NAME,\r\n                    ST" +
                        "ATUS: $scope.InstitutionForm.STATUS,\r\n                    CONTRACT_DATE: FormatS" +
                        "qlDate( $scope.InstitutionForm.CONTRACT_DATE),\r\n                    IPEDS_ID: $s" +
                        "cope.InstitutionForm.IPEDS_ID   \r\n                };\r\n\r\n                $scope.I" +
                        "nstitutionObject = angular.copy(InstitutionObject);\r\n\r\n                var targe" +
                        "tUrl = \"http://lrapdev2013.cloudapp.net/SitePages/StoredProc.aspx?Proc=uspCreate" +
                        "NewInstitution&\" + GenerateQueryString($scope.InstitutionObject);\r\n\r\n           " +
                        "     //$http({ method: \'GET\', url: \'http://lrapdev2013.cloudapp.net/SitePages/St" +
                        "oredProc.aspx?test=1&blah=blob\' }).\r\n                //success(function (data, s" +
                        "tatus, headers, config) {\r\n                //    alert(\"success: \" + data);\r\n   " +
                        "             //}).\r\n                //error(function (data, status, headers, con" +
                        "fig) {\r\n                //    alert(\"error: \" + status);\r\n                //    " +
                        "});\r\n                //alert(encodeURI(targetUrl));\r\n                $(\"#localDi" +
                        "v\").load(encodeURI(targetUrl) + \" #testResponse\", function (response, status, xh" +
                        "r) {\r\n                    //alert(\"In handler\");\r\n                    clearToast" +
                        "s();\r\n                    var storedProcedureResult = \"\" + $(\"#response1\").attr(" +
                        "\'data-sp\');\r\n                    if (storedProcedureResult == \"success\") {\r\n    " +
                        "                    var INSTITUTION_ID_RESULT = \"\" + $(\"#response1\").text();\r\n\r\n" +
                        "                        ShowToasterSuccess(\"New Institution Created: \" + $scope." +
                        "InstitutionObject.INSTITUTION_NAME , \"Redirecting you to their page!\");\r\n       " +
                        "                 $scope.InstitutionForm = {};\r\n                        $(locatio" +
                        "n).attr(\'href\', \"http://lrapdev2013.cloudapp.net/SitePages/InstitutionsDispForm." +
                        "aspx?institutionId=\" + INSTITUTION_ID_RESULT);\r\n                    }\r\n         " +
                        "           else if (storedProcedureResult == \"failure\") {\r\n                     " +
                        "   var i;\r\n                        var errors = $(\"#response1\").text().split(\'|\'" +
                        ");\r\n                        for (i = 0;i < errors.length;++i)\r\n                 " +
                        "       {\r\n                            $scope.InstitutionForm.VALIDATION_TEXT.pus" +
                        "h(errors[i]);\r\n                        }\r\n                        \r\n            " +
                        "            //showToasterError(\"New Institution\", \"\" + $(\"#response1\").text());\r" +
                        "\n                        setTimeout(function () {\r\n                            $" +
                        "(\'[modaltarget=InstitutionModal]\').modal(\'show\');\r\n                            $" +
                        "scope.$apply();\r\n                        }, 2000);\r\n                        \r\n  " +
                        "                      //$scope.$apply();\r\n\r\n                    }\r\n             " +
                        "       else {\r\n                        //alert(\"CONSULT KYLE\");\r\n               " +
                        "         showToasterError(\"New Institution\", \"\" + \"Uncaught expection...Contact " +
                        "Kyle or Jay if problem persists\");\r\n                    }\r\n                   \r\n" +
                        "                });\r\n\r\n\r\n\r\n\r\n\r\n            }\r\n            catch (err) {\r\n       " +
                        "         clearToasts();\r\n                showToasterError(\"Update Failed\", err);" +
                        "\r\n            }\r\n\r\n        };\r\n        /*END Institution Functions */\r\n\r\n\r\n\r\n   " +
                        "     /* eND nEW ANGULAR JS FUNCTONS */\r\n        function FormatTimePeriod(date) " +
                        "{\r\n            var returnString = \"\";\r\n            if (!isNullOrWhiteSpace(date)" +
                        ") {\r\n                var year = date.substring(0, 4);\r\n                var month" +
                        " = date.substring(4, 6);\r\n\r\n\r\n                returnString = (month == \"08\" ? \"A" +
                        "ugust\" : \"January\") + \" \" + year;\r\n            }\r\n            return returnStrin" +
                        "g;\r\n        }\r\n\r\n        function getParameterByName(name) {\r\n            name =" +
                        " name.replace(/[\\[]/, \"\\\\[\").replace(/[\\]]/, \"\\\\]\");\r\n            var regex = ne" +
                        "w RegExp(\"[\\\\?&]\" + name + \"=([^&#]*)\"),\r\n            results = regex.exec(locat" +
                        "ion.search);\r\n            return results == null ? \"\" : decodeURIComponent(resul" +
                        "ts[1].replace(/\\+/g, \" \"));\r\n\r\n        }\r\n\r\n        function isNullOrWhiteSpace(" +
                        "str) {\r\n            if (typeof str !== \'undefined\') {\r\n                return (!" +
                        "str);\r\n            }\r\n            return true;\r\n        }\r\n\r\n        function Ge" +
                        "nerateQueryString(obj) {\r\n            var returnStr = \"\";\r\n            for (var " +
                        "key in obj) {\r\n                if (obj.hasOwnProperty(key)) {\r\n                 " +
                        "   if (!isNullOrWhiteSpace(obj[key])) {\r\n                        //alert(key + \"" +
                        ": \" + fields[key]);\r\n                        //var str = \"\" + obj[key];\r\n       " +
                        "                 returnStr += (\"\" + key + \"=\" + obj[key] + \"&\");\r\n              " +
                        "      }\r\n                }\r\n            }\r\n\r\n            returnStr = returnStr.s" +
                        "ubstring(0, returnStr.length - 1);\r\n            //alert(returnStr);\r\n           " +
                        " return returnStr;\r\n        }\r\n\r\n\r\n\r\n\r\n    }\r\n</script>\r\n\r\n<script type=\"text/ja" +
                        "vascript\">\r\n    toastr.options.timeOut = \"10000000000\";\r\n    toastr.options.clos" +
                        "eButton = true;\r\n    function showToaster(title, message) {\r\n\r\n        toastr.in" +
                        "fo(message, title);\r\n    }\r\n\r\n    function ShowToasterSuccess(title, message) {\r" +
                        "\n        toastr.success(message, title);\r\n    }\r\n\r\n    function clearToasts() {\r" +
                        "\n        toastr.clear();\r\n    }\r\n\r\n    function showToasterError(title, message)" +
                        " {\r\n        toastr.error(message, title);\r\n    }\r\n    function showToasterWarnin" +
                        "g(title, message) {\r\n        toastr.warning(message, title);\r\n    }\r\n    functio" +
                        "n UpdateDate(inputId) {\r\n        //$hiddenInput = $(\"#\" + hiddenInputId).first()" +
                        ";\r\n        var newDate = $(\"#\" + inputId).val();\r\n\r\n        var scope = angular." +
                        "element($(\"#\" + inputId)).scope();\r\n\r\n        scope.$apply(function () {\r\n      " +
                        "     \r\n            scope.InstitutionForm.CONTRACT_DATE = newDate;\r\n           \r\n" +
                        "        });\r\n        //$hiddenInput.trigger(\'change\');\r\n        //angular.elemen" +
                        "t($hiddenInput).scope().$apply();\r\n    }\r\n</script>\r\n\r\n<script type=\"text/javasc" +
                        "ript\">\r\n\r\n    $(document).ready(function () {\r\n        $(\'#demo\').html(\'<table c" +
                        "ellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"display\" id=\"example\"></table>\'" +
                        ");\r\n\r\n        $(\'#example\').dataTable({\r\n            \"data\": dataSet,\r\n         " +
                        "   \"columns\": [            \r\n                { \"title\": \"School\", \"width\": \"20%\"" +
                        " },\r\n                { \"title\": \"Short Name\" },\r\n                { \"title\": \"Cit" +
                        "y/State\" },\r\n                { \"title\": \"Active\" },\r\n                { \"title\": " +
                        "\"Contract Date\" },\r\n                { \"title\": \"Carnegie\" },\r\n                { " +
                        "\"title\": \"Initial Cohort\" },\r\n                { \"title\": \"IPEDS ID\" },\r\n        " +
                        "        { \"title\": \"Freshmen Fee Type\" }\r\n                //{ \"title\": \"# of Enr" +
                        "olled\" }\r\n            ],\r\n            \"lengthMenu\": [[100, 50, 25, 10], [100, 50" +
                        ", 25, 10]]\r\n        });\r\n    });\r\n\r\n</script>\r\n<div data-ng-app data-ng-controll" +
                        "er=\"LrapController\">\r\n\r\n  \r\n    <a href=\"#\" style=\"color: black; margin-top: 4px" +
                        "; padding-right: 5px; padding-left: 5px;\" data-toggle=\"modal\" data-target=\"[moda" +
                        "ltarget=\'InstitutionModal\']\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-plus" +
                        "\"></i>&nbsp;New</a>\r\n    <div id=\"localDiv\" style=\"display:none\" ></div>\r\n\r\n \r\n " +
                        "   \r\n       <div id=\"demo\">\r\n\r\n</div>\r\n\r\n    <!--Institution Modal -->\r\n    <div" +
                        " class=\"modal fade\" modaltarget=\"InstitutionModal\" tabindex=\"-1\" role=\"dialog\" a" +
                        "ria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n        <div style=\"width: 98" +
                        "%\" class=\"modal-dialog\">\r\n            <div class=\"modal-content\">\r\n             " +
                        "   <div class=\"modal-header\">\r\n                    <button type=\"button\" class=\"" +
                        "close\" data-dismiss=\"modal\" aria-hidden=\"true\">\r\n                        &times;" +
                        "\r\n                    </button>\r\n                    <h4 class=\"modal-title\" id=" +
                        "\"H9\">New Institution</h4>\r\n                </div>\r\n                <div class=\"m" +
                        "odal-body\" style=\"width: 90%;\">\r\n                    <form class=\"form-horizonta" +
                        "l\">\r\n                        <fieldset>\r\n                            <div class=" +
                        "\"form-group\" data-ng-hide=\"InstitutionForm.VALIDATION_TEXT.length == 0\">\r\n      " +
                        "                                      <label class=\"col-md-2 control-label\">Erro" +
                        "r<span data-ng-show=\"InstitutionForm.VALIDATION_TEXT.length > 1\">s</span>: </lab" +
                        "el>\r\n                                            <div class=\"col-md-10\">\r\n      " +
                        "                                          <span style=\"color:red\" data-ng-repeat" +
                        "=\"error in Institution.VALIDATION_TEXT\"><b>{{error}}</b><br /></span>  \r\n       " +
                        "                                     </div>\r\n                                   " +
                        "     </div> \r\n                            <div class=\"form-group\">\r\n            " +
                        "                    <label class=\"col-md-2 control-label\"><b>School Name</b></la" +
                        "bel>\r\n                                <div class=\"col-md-10\">\r\n                 " +
                        "                   <input type=\"text\" title=\"InstitutionModalFormId\" data-ng-mod" +
                        "el=\"InstitutionForm.INSTITUTION_NAME\" />\r\n                                </div>" +
                        "\r\n                            </div>\r\n                            <div class=\"fo" +
                        "rm-group\">\r\n                                <label class=\"col-md-2 control-label" +
                        "\"><b>City</b></label>\r\n                                <div class=\"col-md-10\">\r\n" +
                        "                                    <input class=\"form-control\" type=\"text\" data" +
                        "-ng-model=\"InstitutionForm.CITY\">\r\n                                </div>\r\n     " +
                        "                       </div>\r\n                            <div class=\"form-grou" +
                        "p\">\r\n                                <label class=\"col-md-2 control-label\"><b>St" +
                        "ate/Province</b></label>\r\n                                <div class=\"col-md-10\"" +
                        ">\r\n                                    <input data-ng-model=\"InstitutionForm.STA" +
                        "TE_PROVINCE\" class=\"form-control\" type=\"text\">\r\n                                " +
                        "</div>\r\n                            </div>\r\n                            <div cla" +
                        "ss=\"form-group\">\r\n                                <label class=\"col-md-2 control" +
                        "-label\"><b>Short Name</b></label>\r\n                                <div class=\"c" +
                        "ol-md-10\">\r\n                                    <input class=\"form-control\" type" +
                        "=\"text\" data-ng-model=\"InstitutionForm.SHORT_NAME\">\r\n                           " +
                        "     </div>\r\n                            </div>\r\n                            <di" +
                        "v class=\"form-group\">\r\n                                <label class=\"col-md-2 co" +
                        "ntrol-label\"><b>Status</b></label>\r\n                                <div class=\"" +
                        "col-md-5\">\r\n                                    <select data-ng-model=\"Instituti" +
                        "onForm.STATUS\" data-ng-options=\"InstitutionStatusOption.id as InstitutionStatusO" +
                        "ption.label for InstitutionStatusOption in InstitutionStatusOptions\">\r\n         " +
                        "                           </select>\r\n                                </div>\r\n  " +
                        "                          </div>\r\n                            <div class=\"form-g" +
                        "roup\">\r\n                                <label class=\"col-md-2 control-label\"><b" +
                        ">Contract Date</b></label>\r\n                                <div class=\"col-md-1" +
                        "0\">\r\n                                                \r\n                         " +
                        "               <div class=\"input-icon-right\">\r\n                                 " +
                        "                       <i class=\"fa fa-calendar\"></i>\r\n                         " +
                        "                               <input id=\"InstitutionFormCONTRACT_DATE\" data-ng-" +
                        "model=\"InstitutionForm.CONTRACT_DATE\" onchange=\"UpdateDate(\'InstitutionFormCONTR" +
                        "ACT_DATE\')\" type=\"text\" name=\"mydate\" class=\"form-control datepicker\" data-datef" +
                        "ormat=\"mm/dd/yy\" />                                                             " +
                        "                                                                             \r\n " +
                        "                                                   </div>\r\n                     " +
                        "              \r\n                                    \r\n                          " +
                        "      </div>\r\n                            </div>\r\n              \r\n              " +
                        "               <div class=\"form-group\">\r\n                                <label " +
                        "class=\"col-md-2 control-label\"><b>IPEDS ID</b></label>\r\n                        " +
                        "        <div class=\"col-md-10\">\r\n                                    <input clas" +
                        "s=\"form-control\" type=\"text\" data-ng-model=\"InstitutionForm.IPEDS_ID\">          " +
                        "                       \r\n                                </div>\r\n               " +
                        "             </div>\r\n                           \r\n\r\n                        </fi" +
                        "eldset>\r\n\r\n                    </form>\r\n\r\n                </div>\r\n              " +
                        "  <div class=\"modal-footer\">\r\n                    <button type=\"button\" class=\"b" +
                        "tn btn-default\" data-ng-click=\"HideModal(\'[modaltarget=InstitutionModal]\');\">\r\n " +
                        "                       Cancel\r\n                    </button>\r\n                  " +
                        "  <button type=\"button\" class=\"btn btn-primary\" data-ng-click=\"UpdateInstitution" +
                        "();HideModal(\'[modaltarget=InstitutionModal]\');\">\r\n                        Submi" +
                        "t\r\n                    </button>\r\n                </div>\r\n            </div>\r\n  " +
                        "          <!-- /.modal-content -->\r\n        </div>\r\n        <!-- /.modal-dialog " +
                        "-->\r\n    </div>\r\n    <!--End Institution  Modal -->\r\n    </div>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
